------------------------------------------------------------------------------
--  Copyright (c) 2018 by Paul Scherrer Institute, Switzerland
--  All rights reserved.
--  Authors: Oliver Bruendler
------------------------------------------------------------------------------

------------------------------------------------------------
-- Testbench generated by TbGen.py
------------------------------------------------------------
-- see Library/Python/TbGenerator

------------------------------------------------------------
-- Libraries
------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.psi_common_math_pkg.all;
use work.psi_common_logic_pkg.all;
use work.psi_tb_compare_pkg.all;

------------------------------------------------------------
-- Entity Declaration
------------------------------------------------------------
entity psi_common_arb_priority_tb is
end entity;

------------------------------------------------------------
-- Architecture
------------------------------------------------------------
architecture sim of psi_common_arb_priority_tb is
  -- *** Fixed Generics ***
  constant size_g           : natural := 5;
  constant out_reg_g : boolean := true;

  -- *** TB Control ***
  signal TbRunning            : boolean                  := True;
  signal NextCase             : integer                  := -1;
  signal ProcessDone          : std_logic_vector(0 to 0) := (others => '0');
  constant AllProcessesDone_c : std_logic_vector(0 to 0) := (others => '1');
  constant TbProcNr_stimuli_c : integer                  := 0;

  -- *** DUT Signals ***
  signal clk_i     : std_logic                             := '1';
  signal rst_i     : std_logic                             := '1';
  signal req_i : std_logic_vector(size_g - 1 downto 0) := (others => '0');
  signal grant_o   : std_logic_vector(size_g - 1 downto 0) := (others => '0');

begin
  ------------------------------------------------------------
  -- DUT Instantiation
  ------------------------------------------------------------
  i_dut : entity work.psi_common_arb_priority
    generic map(
      size_g           => size_g,
      out_reg_g => out_reg_g
    )
    port map(
      clk_i     => clk_i,
      rst_i     => rst_i,
      req_i => req_i,
      grant_o   => grant_o
    );

  ------------------------------------------------------------
  -- Testbench Control !DO NOT EDIT!
  ------------------------------------------------------------
  p_tb_control : process
  begin
    wait until rst_i = '0';
    wait until ProcessDone = AllProcessesDone_c;
    TbRunning <= false;
    wait;
  end process;

  ------------------------------------------------------------
  -- Clocks !DO NOT EDIT!
  ------------------------------------------------------------
  p_clock_Clk : process
    constant Frequency_c : real := real(100e6);
  begin
    while TbRunning loop
      wait for 0.5 * (1 sec) / Frequency_c;
      clk_i <= not clk_i;
    end loop;
    wait;
  end process;

  ------------------------------------------------------------
  -- Resets
  ------------------------------------------------------------
  p_rst_Rst : process
  begin
    wait for 1 us;
    -- Wait for two clk edges to ensure reset is active for at least one edge
    wait until rising_edge(clk_i);
    wait until rising_edge(clk_i);
    rst_i <= '0';
    wait;
  end process;

  ------------------------------------------------------------
  -- Processes
  ------------------------------------------------------------
  -- *** stimuli ***
  p_stimuli : process
  begin
    -- start of process !DO NOT EDIT
    wait until rst_i = '0';

    -- Single Bit
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("00000", grant_o, "Wrong value after reset");
    wait until rising_edge(clk_i);
    wait for 1 ns;
    req_i <= "01000";
    StdlvCompareStdlv("00000", grant_o, "grant_o asserted without register delay");
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("01000", grant_o, "grant_o 1 Wrong");
    wait until rising_edge(clk_i);
    wait for 1 ns;
    req_i <= "00000";
    StdlvCompareStdlv("01000", grant_o, "grant_o 2 Wrong");
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("00000", grant_o, "grant_o not de-asserted");

    -- Multi Bit
    wait until rising_edge(clk_i);
    wait for 1 ns;
    req_i <= "10111";
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("10000", grant_o, "grant_o 3 Wrong");
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("10000", grant_o, "grant_o 4 Wrong");
    req_i <= "00111";
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("00100", grant_o, "grant_o 4 Wrong");
    req_i <= "00011";
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("00010", grant_o, "grant_o 4 Wrong");
    req_i <= "10001";
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("10000", grant_o, "grant_o 4 Wrong");
    req_i <= "00001";
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("00001", grant_o, "grant_o 4 Wrong");
    req_i <= "00000";
    wait until rising_edge(clk_i);
    wait for 1 ns;
    StdlvCompareStdlv("00000", grant_o, "grant_o 4 Wrong");
    wait for 1 us;

    -- end of process !DO NOT EDIT!
    ProcessDone(TbProcNr_stimuli_c) <= '1';
    wait;
  end process;

end;
